# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build using node.js cli

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - name: Installing dependencies
    #   run: npm ci

    # - name: Build and publish to Github Pages
    #   run: npm run deploy
    # # - name: Tar the shit out of the build folder, man.
    #   run: tar -czf build.tar.gz public/

    # - name: Copy folder content recursively to remote
    #   uses: garygrossgarten/github-action-scp@release
    #   with:
    #     local: build.tar.gz
    #     remote: /var/www/joohan.kim/build.tar.gz
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     privateKey: ${{ secrets.SSHKEY }}

    # - name: Copy file via scp
    #   uses: appleboy/scp-action@master
    #   env:
    #     HOST: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     PASSWORD: ${{ secrets.PASSWORD }}
    #     PORT: 22
    #   with:
    #     source: "build.tar.gz"
    #     target: "/var/www/joohan.kim/"
    #     # KEY: ${{ secrets.SSHKEY }}
    #     # with:

    # - name: The magic is happening here
    #   uses: appleboy/ssh-action@master
    #   with:
    #     HOST: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     PASSWORD: ${{ secrets.PASSWORD }}
    #     script: cd /var/www/joohan.kim && source deploy.sh
